version: "3.7"
services:

  # Port numbers (normal port number + 40000):
  # - mysql    43306
  # - postgres 45432
  mysql:
    # See https://hub.docker.com/_/mysql
    image: mysql:latest
    container_name: schema-test-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 127.0.0.1:43306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password-123

  postgres:
    # See https://hub.docker.com/_/postgres
    image: postgres:latest
    container_name: schema-test-postgres
    ports:
      - 127.0.0.1:45432:5432
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
